name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        terraform-version: [1.3.2]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Deploy resources via Terraform
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve
