name: infra

on:
  push:
    paths:
      - infra/**

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        terraform-version: [1.3.2]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Check Terraform codes
        run: |
          cd infra
          terraform init
          terraform fmt -check -recursive || exit $?
          terraform validate || exit $?
